### ISSUE TITLE
Add how to manually fix fixable 

### ISSUE THREAD

**Issue by PauliusMacernis** [digitronas/akeneo-coding-standard#21]
![image](https://user-images.githubusercontent.com/8057568/68604605-8d082600-04b3-11ea-92c6-117b2af3dacb.png)

Just simply adding `--fix` does not work.
(Following instructions provided by README.md)

**Comment by jbieliauskas** [comment]
Right, `grumphp` doesn't lint files, [ecs does](https://github.com/Symplify/EasyCodingStandard#2-run-in-cli). So, this should be:

`$ vendor/bin/ecs check src --config=/path/to/config --fix`

**Comment by PauliusMacernis** [comment]
Yep, I just found it to be run like this (on the project in where this standard is installed as described in readme.md):
`$ php ./vendor/bin/ecs check --config vendor/digitronas/akeneo-coding-standard/ecs.yml app/AppCache.php`

and the following would fix:
`$ php ./vendor/bin/ecs check --config vendor/digitronas/akeneo-coding-standard/ecs.yml --fix app/AppCache.php`

Is it possible to somehow load the existing project's `grumphp.yml` by default?

**Comment by jbieliauskas** [comment]
Moved this to #24
